apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "replic2.fullname" . }}-backups
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "replic2.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
