{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "replic2.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson | required "imagePullSecret.dockerconfigjson is required when imagePullSecret.create=true" }}
{{- end }}
